In [1]:
import numpy as np

In [2]:
#Ques1
temp = np.array([[[[14,20],[15,29],[6,21],[13,22],[13,26],[7,25],[11,22]] , [[9,30],[9,23],[15,21],[-13,24],[7,25],[10,26],[10,25]] , [[15,22],[12,24],[7,27],[10,23],[14,28],[9,28],[9,22]] , [[14,27],[12,23],[13,20],[9,29],[10,30],[15,31],[6,27]]],
                 [[[9,26],[14,20],[9,28],[10,23],[12,26],[15,21],[11,29]] , [[6,27],[8,32],[9,21],[8,28],[8,31],[15,32],[15,29]] , [[13,27],[7,27],[11,26],[9,30],[13,27],[7,31],[15,30]] , [[8,22],[12,31],[8,32],[6,29],[7,24],[7,24],[14,25]]],
                 [[[4,20],[5,21],[5,21],[4,20],[4,22],[2,7],[21,7]] , [[2,20],[2,18],[2,20],[3,20],[3,18],[8,2],[22,2]] , [[3,18],[5,21],[6,22],[7,20],[6,22],[7,4],[18,3]] , [[5,20],[6,20],[8,21],[6,20],[2,21],[3,3],[21,7]]],
                 [[[9,20],[12,22],[-10,21],[8,21],[12,19],[10,71],[21,12]] , [[11,22],[7,18],[7,21],[10,19],[12,21],[12,10],[21,10]] , [[12,21],[9,18],[9,19],[12,22],[8,21],[10,8],[21,12]] , [[8,18],[9,21],[9,20],[9,18],[11,19],[7,8],[19,11]]]])

In [3]:
temp

array([[[[ 14,  20],
         [ 15,  29],
         [  6,  21],
         [ 13,  22],
         [ 13,  26],
         [  7,  25],
         [ 11,  22]],

        [[  9,  30],
         [  9,  23],
         [ 15,  21],
         [-13,  24],
         [  7,  25],
         [ 10,  26],
         [ 10,  25]],

        [[ 15,  22],
         [ 12,  24],
         [  7,  27],
         [ 10,  23],
         [ 14,  28],
         [  9,  28],
         [  9,  22]],

        [[ 14,  27],
         [ 12,  23],
         [ 13,  20],
         [  9,  29],
         [ 10,  30],
         [ 15,  31],
         [  6,  27]]],


       [[[  9,  26],
         [ 14,  20],
         [  9,  28],
         [ 10,  23],
         [ 12,  26],
         [ 15,  21],
         [ 11,  29]],

        [[  6,  27],
         [  8,  32],
         [  9,  21],
         [  8,  28],
         [  8,  31],
         [ 15,  32],
         [ 15,  29]],

        [[ 13,  27],
         [  7,  27],
         [ 11,  26],
         [  9,  30],
         [ 13,  27],

In [4]:
#Ques2
print(temp.ndim)
temp.shape

4


(4, 4, 7, 2)

In [5]:
#Ques3
temp[:,:1,:,:]

array([[[[ 14,  20],
         [ 15,  29],
         [  6,  21],
         [ 13,  22],
         [ 13,  26],
         [  7,  25],
         [ 11,  22]]],


       [[[  9,  26],
         [ 14,  20],
         [  9,  28],
         [ 10,  23],
         [ 12,  26],
         [ 15,  21],
         [ 11,  29]]],


       [[[  4,  20],
         [  5,  21],
         [  5,  21],
         [  4,  20],
         [  4,  22],
         [  2,   7],
         [ 21,   7]]],


       [[[  9,  20],
         [ 12,  22],
         [-10,  21],
         [  8,  21],
         [ 12,  19],
         [ 10,  71],
         [ 21,  12]]]])

In [6]:
#Ques4
temp[:,:,1:2,:]

array([[[[15, 29]],

        [[ 9, 23]],

        [[12, 24]],

        [[12, 23]]],


       [[[14, 20]],

        [[ 8, 32]],

        [[ 7, 27]],

        [[12, 31]]],


       [[[ 5, 21]],

        [[ 2, 18]],

        [[ 5, 21]],

        [[ 6, 20]]],


       [[[12, 22]],

        [[ 7, 18]],

        [[ 9, 18]],

        [[ 9, 21]]]])

In [7]:
#Ques 5
temp[1::2,:,:5,1:]

array([[[[26],
         [20],
         [28],
         [23],
         [26]],

        [[27],
         [32],
         [21],
         [28],
         [31]],

        [[27],
         [27],
         [26],
         [30],
         [27]],

        [[22],
         [31],
         [32],
         [29],
         [24]]],


       [[[20],
         [22],
         [21],
         [21],
         [19]],

        [[22],
         [18],
         [21],
         [19],
         [21]],

        [[21],
         [18],
         [19],
         [22],
         [21]],

        [[18],
         [21],
         [20],
         [18],
         [19]]]])

In [8]:
#Ques 6
nov_temp = temp[:1,:,:,:1]
min_temp = nov_temp<8


In [9]:
#Ques 7
max_temp=temp[1:3,:,:,1:]
maximum_temp = max_temp>20
max_temp[maximum_temp]

array([26, 28, 23, 26, 21, 29, 27, 32, 21, 28, 31, 32, 29, 27, 27, 26, 30,
       27, 31, 30, 22, 31, 32, 29, 24, 24, 25, 21, 21, 22, 21, 22, 22, 21,
       21])

In [10]:
#ques8


In [11]:
#ques9

In [12]:
#ques10

In [13]:
#ques11

In [14]:
#ques12
aver=temp[:,:,:,1:]
np.average(aver)

21.794642857142858

In [15]:
#ques13
week_min = temp[1:2,:,:,:1]
averages = np.mean(week_min, axis=(2,3))
averages

array([[11.42857143,  9.85714286, 10.71428571,  8.85714286]])

In [16]:
#ques14
overall_avg = temp[1:3,:,:,:]
np.average(overall_avg)

14.946428571428571

In [17]:
#ques15
least_temp = temp[1:3,:,:,:]
np.min(least_temp)

2

In [18]:
#ques16
max_temp = temp[2:,:,:,:]
maximum = np.amax(max_temp)
print(maximum)

(np.where(temp[3]==np.amax(temp[3])))

71


(array([0], dtype=int64), array([5], dtype=int64), array([1], dtype=int64))

In [19]:
#ques17
temp_nov = temp[:1,:,:,:]
avg_temp = np.average(temp_nov)
max_temp_nov = temp[:1,:,:,1:]
result = (max_temp > avg_temp)

In [20]:
#ques18
temp.reshape((4,7,4,2))

array([[[[ 14,  20],
         [ 15,  29],
         [  6,  21],
         [ 13,  22]],

        [[ 13,  26],
         [  7,  25],
         [ 11,  22],
         [  9,  30]],

        [[  9,  23],
         [ 15,  21],
         [-13,  24],
         [  7,  25]],

        [[ 10,  26],
         [ 10,  25],
         [ 15,  22],
         [ 12,  24]],

        [[  7,  27],
         [ 10,  23],
         [ 14,  28],
         [  9,  28]],

        [[  9,  22],
         [ 14,  27],
         [ 12,  23],
         [ 13,  20]],

        [[  9,  29],
         [ 10,  30],
         [ 15,  31],
         [  6,  27]]],


       [[[  9,  26],
         [ 14,  20],
         [  9,  28],
         [ 10,  23]],

        [[ 12,  26],
         [ 15,  21],
         [ 11,  29],
         [  6,  27]],

        [[  8,  32],
         [  9,  21],
         [  8,  28],
         [  8,  31]],

        [[ 15,  32],
         [ 15,  29],
         [ 13,  27],
         [  7,  27]],

        [[ 11,  26],
         [  9,  30],
         [

In [21]:
#ques19
fah_temp = temp * 1.8 + 32
fah_temp

array([[[[ 57.2,  68. ],
         [ 59. ,  84.2],
         [ 42.8,  69.8],
         [ 55.4,  71.6],
         [ 55.4,  78.8],
         [ 44.6,  77. ],
         [ 51.8,  71.6]],

        [[ 48.2,  86. ],
         [ 48.2,  73.4],
         [ 59. ,  69.8],
         [  8.6,  75.2],
         [ 44.6,  77. ],
         [ 50. ,  78.8],
         [ 50. ,  77. ]],

        [[ 59. ,  71.6],
         [ 53.6,  75.2],
         [ 44.6,  80.6],
         [ 50. ,  73.4],
         [ 57.2,  82.4],
         [ 48.2,  82.4],
         [ 48.2,  71.6]],

        [[ 57.2,  80.6],
         [ 53.6,  73.4],
         [ 55.4,  68. ],
         [ 48.2,  84.2],
         [ 50. ,  86. ],
         [ 59. ,  87.8],
         [ 42.8,  80.6]]],


       [[[ 48.2,  78.8],
         [ 57.2,  68. ],
         [ 48.2,  82.4],
         [ 50. ,  73.4],
         [ 53.6,  78.8],
         [ 59. ,  69.8],
         [ 51.8,  84.2]],

        [[ 42.8,  80.6],
         [ 46.4,  89.6],
         [ 48.2,  69.8],
         [ 46.4,  82.4],
         [ 46

In [22]:
#ques20
dec_temp = temp[1:2,:,:,:]
avg_dec_temp = np.average((dec_temp))
avg_dec_temp

18.642857142857142

In [23]:
#ques21
 

In [24]:
#ques22
min_temp = temp[:,:,:,:1]
max_temp = temp[:,:,:,1:]
res_temp = max_temp - min_temp
res_temp

array([[[[  6],
         [ 14],
         [ 15],
         [  9],
         [ 13],
         [ 18],
         [ 11]],

        [[ 21],
         [ 14],
         [  6],
         [ 37],
         [ 18],
         [ 16],
         [ 15]],

        [[  7],
         [ 12],
         [ 20],
         [ 13],
         [ 14],
         [ 19],
         [ 13]],

        [[ 13],
         [ 11],
         [  7],
         [ 20],
         [ 20],
         [ 16],
         [ 21]]],


       [[[ 17],
         [  6],
         [ 19],
         [ 13],
         [ 14],
         [  6],
         [ 18]],

        [[ 21],
         [ 24],
         [ 12],
         [ 20],
         [ 23],
         [ 17],
         [ 14]],

        [[ 14],
         [ 20],
         [ 15],
         [ 21],
         [ 14],
         [ 24],
         [ 15]],

        [[ 14],
         [ 19],
         [ 24],
         [ 23],
         [ 17],
         [ 17],
         [ 11]]],


       [[[ 16],
         [ 16],
         [ 16],
         [ 16],
         [ 18],
    

In [25]:
#ques23
max_temp = temp[:,:,:,1:]
max_temp
diff_max = np.ediff1d((max_temp))
diff_max

array([  9,  -8,   1,   4,  -1,  -3,   8,  -7,  -2,   3,   1,   1,  -1,
        -3,   2,   3,  -4,   5,   0,  -6,   5,  -4,  -3,   9,   1,   1,
        -4,  -1,  -6,   8,  -5,   3,  -5,   8,  -2,   5, -11,   7,   3,
         1,  -3,  -2,   0,  -1,   4,  -3,   4,  -1,  -8,   9,   1,  -3,
        -5,   0,   1,  -5,   1,   0,  -1,   2, -15,   0,  13,  -2,   2,
         0,  -2, -16,   0,  16,   3,   1,  -2,   2, -18,  -1,  17,   0,
         1,  -1,   1, -18,   4,  13,   2,  -1,   0,  -2,  52, -59,  10,
        -4,   3,  -2,   2, -11,   0,  11,  -3,   1,   3,  -1, -13,   4,
         6,   3,  -1,  -2,   1, -11,   3])

In [26]:
#ques24
min_temp = temp[:,:,:,:1]
min_temp
diff_min = np.ediff1d((min_temp))
diff_min

array([  1,  -9,   7,   0,  -6,   4,  -2,   0,   6, -28,  20,   3,   0,
         5,  -3,  -5,   3,   4,  -5,   0,   5,  -2,   1,  -4,   1,   5,
        -9,   3,   5,  -5,   1,   2,   3,  -4,  -5,   2,   1,  -1,   0,
         7,   0,  -2,  -6,   4,  -2,   4,  -6,   8,  -7,   4,  -4,  -2,
         1,   0,   7, -10,   1,   0,  -1,   0,  -2,  19, -19,   0,   0,
         1,   0,   5,  14, -19,   2,   1,   1,  -1,   1,  11, -13,   1,
         2,  -2,  -4,   1,  18, -12,   3, -22,  18,   4,  -2,  11, -10,
        -4,   0,   3,   2,   0,   9,  -9,  -3,   0,   3,  -4,   2,  11,
       -13,   1,   0,   0,   2,  -4,  12])

In [27]:
#ques25
res_arr = np.concatenate((diff_max,diff_min))
res_arr

array([  9,  -8,   1,   4,  -1,  -3,   8,  -7,  -2,   3,   1,   1,  -1,
        -3,   2,   3,  -4,   5,   0,  -6,   5,  -4,  -3,   9,   1,   1,
        -4,  -1,  -6,   8,  -5,   3,  -5,   8,  -2,   5, -11,   7,   3,
         1,  -3,  -2,   0,  -1,   4,  -3,   4,  -1,  -8,   9,   1,  -3,
        -5,   0,   1,  -5,   1,   0,  -1,   2, -15,   0,  13,  -2,   2,
         0,  -2, -16,   0,  16,   3,   1,  -2,   2, -18,  -1,  17,   0,
         1,  -1,   1, -18,   4,  13,   2,  -1,   0,  -2,  52, -59,  10,
        -4,   3,  -2,   2, -11,   0,  11,  -3,   1,   3,  -1, -13,   4,
         6,   3,  -1,  -2,   1, -11,   3,   1,  -9,   7,   0,  -6,   4,
        -2,   0,   6, -28,  20,   3,   0,   5,  -3,  -5,   3,   4,  -5,
         0,   5,  -2,   1,  -4,   1,   5,  -9,   3,   5,  -5,   1,   2,
         3,  -4,  -5,   2,   1,  -1,   0,   7,   0,  -2,  -6,   4,  -2,
         4,  -6,   8,  -7,   4,  -4,  -2,   1,   0,   7, -10,   1,   0,
        -1,   0,  -2,  19, -19,   0,   0,   1,   0,   5,  14, -1